# Generated by Django 5.0.1 on 2024-04-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_reply_reply_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='contdb',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.regdb'),
        ),
    ]
